### ISSUE TITLE
Unable to run boilerplate code from README file.

### ISSUE THREAD

**Issue by RatanShreshtha** [tusharsanap7/redis-acl#1]
I am trying out your new redis ACL library but I am unable to run boilerplate code from the README.md.

Here is the thing I am trying out...

```
let acl = require('redis-acl');

// Connect with redis instance
let redisConnectionConf = {
	"host": "127.0.0.1",
	"port": 6379
};
acl = new acl(redisConnectionConf);

// add new resource
acl.addResource("blogs",(err, res)=>{});

// add child resource and create resource hierarhy
// creating child resource implicitly creates parents
acl.addChildResource("blogs", "tech-blogs", (err, res)=>{});

acl.addChildResource("tech-blogs", "device-reviews", (err, res)=>{});

acl.addChildResource("tech-blogs", "os-reviews", (err, res)=>{});

acl.addRole("admin", (err, res)=>{});

acl.addTask("admin", ["view","modify","delete"], (err, res)=>{});

acl.allowResourceAccess("david", "device-reviews", ["admin"], (err, res)=>{});


acl.getRole("david", "device-reviews", (err, res)=>{
    // this will return an array of available roles
    // res => ["admin"]
    console.log("-----------", res)
})
```

And here is the output ...

```
{ ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/home/rkulshreshtha/Desktop/mystuff/redis_test/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/rkulshreshtha/Desktop/mystuff/redis_test/node_modules/redis-parser/lib/parser.js:303:14)
  command: 'EXEC',
  code: 'EXECABORT',
  errors: 
   [ { ReplyError: ERR wrong number of arguments for 'sadd' command
    at parseError (/home/rkulshreshtha/Desktop/mystuff/redis_test/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/rkulshreshtha/Desktop/mystuff/redis_test/node_modules/redis-parser/lib/parser.js:303:14) command: 'SADD', args: [Array], code: 'ERR', position: 0 } ] }
----------- [ 'admin' ]

```

I am running a linux box with fedora 27 and node v8.9.3 and redis version 4.0.

**Comment by tusharsanap7** [comment]
Thanks, @RatanShreshtha 
The issue has been fixed!
